version: "2.3"

services:
  web:
    build: ../../
    ports:
      - "443:443"
      - "80:80"

  translate:
    image: "libretranslate/libretranslate:1.3.10"
    environment:
      - LT_LOAD_ONLY=en,fr,es,de,ru,ja,ko,zh # Only load few languages
    ports:
      - "8080:5000"
    healthcheck:
      test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']
